function(copy_libs libraries_list)
    foreach(lib_path ${libraries_list})
        install(CODE "execute_process(COMMAND cp ${lib_path} ${CMAKE_CURRENT_BINARY_DIR}/libs/)")
    endforeach()
endfunction()
